### ISSUE TITLE
Set up DynamoDB in Console

### ISSUE THREAD

**Issue by heiheihang** [LalaCuteGroup/lala-referral#3]
We need to design the schema for the following tables:
* Companies
* Promoted Openings
* User Profiles
* Referrals

**Comment by heiheihang** [comment]
DynamoDB tables set up in console [here](https://us-east-1.console.aws.amazon.com/dynamodbv2/home?region=us-east-1#tables)

These tables have suffix `-test`, and are used for testing in console only. We need to migrate these tables to CDK provisioning in the future.

**Comment by slience-suzuka** [comment]
> DynamoDB tables set up in console [here](https://us-east-1.console.aws.amazon.com/dynamodbv2/home?region=us-east-1#tables)
> 
> These tables have suffix `-test`, and are used for testing in console only. We need to migrate these tables to CDK provisioning in the future.

cannot access,
You have not created IAM user for me I think
