### ISSUE TITLE
Create React Project Template + CICD in AWS Amplify

### ISSUE THREAD

**Issue by heiheihang** [LalaCuteGroup/lala-referral#8]
We need a static website to display the features of our product. 
We need to set up a CICD for the react project in AWS Amplify

**Comment by ocwilsonchow** [comment]
what's up cowsep

**Comment by heiheihang** [comment]
Amplify Config is [here](https://us-east-1.console.aws.amazon.com/amplify/home?code=14f64db6027dc73e186e&installation_id=27268568&region=us-east-1&setup_action=install#/d3mjgffrc8jv7c)

Deployed on [here](https://main.d3mjgffrc8jv7c.amplifyapp.com/)

**Comment by heiheihang** [comment]
Closing this issue as everything is configured in the console.
